enum EPeriodType {
  SINGLE = 'SINGLE',
  DAYLY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BI_WEEKLY = 'BI_WEEKLY',
  MONTHLY = 'MONTHLY',
  BI_MONTHLY = 'BI_MONTHLY',
  TRIMESTER = 'TRIMESTER',
  QUARTERLY = 'QUARTERLY',
  SEMI_ANNUALLY = 'SEMI_ANNUALLY',
  YEARLY = 'YEARLY',
  CUSTOM = 'CUSTOM',
}

export default EPeriodType;
