export const PORTFOLIO_CONSTANTS = {
  DEFAULT_CURRENCY: 'USD',
  MAX_PORTFOLIOS_PER_USER: 10,
  TRANSACTION_TYPES: {
    BUY: 'BUY',
    SELL: 'SELL',
    DIVIDEND: 'DIVIDEND',
    SPLIT: 'SPLIT',
    TRANSFER_IN: 'TRANSFER_IN',
    TRANSFER_OUT: 'TRANSFER_OUT',
  },
  ASSET_CATEGORIES: {
    CRYPTO: 'CRYPTO',
    STOCK: 'STOCK',
    ETF: 'ETF',
    COMMODITY: 'COMMODITY',
    FOREX: 'FOREX',
  },
  ASSET_TYPES: {
    CRYPTOCURRENCY: 'CRYPTOCURRENCY',
    EQUITY: 'EQUITY',
    INDEX_FUND: 'INDEX_FUND',
    PRECIOUS_METAL: 'PRECIOUS_METAL',
    CURRENCY_PAIR: 'CURRENCY_PAIR',
  },
  PRICE_UPDATE_SCHEDULE: {
    MORNING_UTC: '06:00',
    EVENING_UTC: '22:00',
  },
  SNAPSHOT_DATE_FORMAT: 'YYYY-MM-DD',
} as const;
