name: Auto Merge Dependabot

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check if PR is from Dependabot
        run: |
          AUTHOR=$(jq -r ".pull_request.user.login" "$GITHUB_EVENT_PATH")
          if [[ "$AUTHOR" != "dependabot[bot]" ]]; then
            echo "PR is not from Dependabot, skipping merge."
            exit 1
          fi

      - name: Approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        continue-on-error: true
